apiVersion: v1
kind: Namespace
metadata:
  name: fetch-k8s-resource
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fetch-k8s-resource
  namespace: fetch-k8s-resource
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fetch-k8s-resource
  namespace: fetch-k8s-resource
subjects:
- kind: ServiceAccount
  name: fetch-k8s-resource
  namespace: fetch-k8s-resource
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fetch-k8s-resource
  name: fetch-k8s-resource
  namespace: fetch-k8s-resource
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetch-k8s-resource
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fetch-k8s-resource
    spec:
      serviceAccountName: fetch-k8s-resource
      containers:
      - image: shovan1995/fetch-k8s-resource:v4.2
        name: fetch-k8s-resource
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 200m
            memory: 200Mi
      restartPolicy: Always
